package com.upandcoding.broadsql.controller.shell.scripts;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * SPRINT 0110A: a SQL statement whose {@code ${name}} references were turned into JDBC {@code ?} markers
 * generated by BroadSQL, with the values to bind to them, in marker order (spec section 9.2). Built by
 * {@link SqlReferences#prepare}; executed by the {@code DatabaseConnection} methods that take one.
 */
public final class PreparedSql {

	private final String originalText;
	private final String jdbcText;
	private final List<ScriptValue> binds;
	private final Map<String, ScriptValue> referenced;

	PreparedSql(String originalText, String jdbcText, List<ScriptValue> binds, LinkedHashMap<String, ScriptValue> referenced) {
		this.originalText = originalText;
		this.jdbcText = jdbcText;
		this.binds = Collections.unmodifiableList(binds);
		this.referenced = Collections.unmodifiableMap(referenced);
	}

	/** A statement without references, prepared as written (the scalar query of {@code LET}). */
	public static PreparedSql unbound(String text) {
		return new PreparedSql(text, text, List.of(), new LinkedHashMap<>());
	}

	/** The statement as written (with its {@code ${...}}): what is displayed, logged and error-rendered. */
	public String getOriginalText() {
		return originalText;
	}

	/** The SQL handed to {@code prepareStatement}. */
	public String getJdbcText() {
		return jdbcText;
	}

	/** One value per generated marker, left to right. */
	public List<ScriptValue> getBinds() {
		return binds;
	}

	/** Each distinct referenced variable (display spelling) with the value bound, in first-reference order. */
	public Map<String, ScriptValue> getReferenced() {
		return referenced;
	}
}
