package com.upandcoding.broadsql.controller.shell.scripts;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.function.BooleanSupplier;

import com.upandcoding.broadsql.controller.errors.BroadSQLException;
import com.upandcoding.broadsql.dao.api.ApiSessionVariablesHolder;

/**
 * SPRINT 0110A: turns the {@code ${name}} references of a SQL text into typed JDBC binds (spec sections 9.2
 * to 9.6), for the three SQL positions of spec section 2: the SQL path ({@code CommandDefault}), the query of
 * {@code LET}, the parenthesized source query of {@code DUMP}/{@code PULL}. A reference is never textual
 * replacement: each one becomes a {@code ?} generated by BroadSQL and its value is bound, so a value can never
 * change the structure of the statement.
 *
 * <p>Raw {@code ?} characters written by the user (normal text only) are not BroadSQL syntax (spec 9.6): a
 * statement without references is not touched at all; with references, on the PostgreSQL JDBC driver every
 * raw {@code ?} is written {@code ??} (pgjdbc's escape for a literal {@code ?}, so the {@code ?}, {@code ?|},
 * {@code ?&} operators keep working); on any other driver the statement is refused before execution.
 */
public final class SqlReferences {

	private SqlReferences() {
	}

	/**
	 * @param pgjdbc consulted only when the statement has references and raw {@code ?}: whether the current
	 *               connection's driver is pgjdbc
	 * @return {@code null} when {@code sql} has no reference (the statement runs exactly as today)
	 * @throws BroadSQLException a malformed or undefined reference, or raw {@code ?} refused (spec 9.6 rule 3);
	 *                           nothing has been sent to the database
	 */
	public static PreparedSql prepare(String sql, ScriptVariables variables, BooleanSupplier pgjdbc) throws BroadSQLException {
		VariableReferenceScanner.Scan scan = VariableReferenceScanner.scan(sql);
		if (!scan.hasReferences()) {
			return null;
		}
		List<ScriptValue> binds = new ArrayList<>();
		LinkedHashMap<String, ScriptValue> referenced = new LinkedHashMap<>();
		for (VariableReferenceScanner.Occurrence occurrence : scan.getOccurrences()) {
			if (occurrence.isMalformed()) {
				throw malformed(occurrence.text());
			}
			ScriptValue value = variables.get(occurrence.name());
			if (value == null) {
				throw undefined(occurrence.name());
			}
			binds.add(value);
			referenced.putIfAbsent(variables.displayName(occurrence.name()), value);
		}
		boolean escapeQuestionMarks = false;
		if (!scan.getRawQuestionMarks().isEmpty()) {
			if (!pgjdbc.getAsBoolean()) {
				throw new BroadSQLException("Raw ? placeholders cannot be combined with ${...} variable references in this version: "
						+ "write the value as a ${name} reference, or remove the variable references from this statement");
			}
			escapeQuestionMarks = true;
		}
		StringBuilder jdbc = new StringBuilder(sql.length() + 8);
		int copied = 0;
		int q = 0;
		List<Integer> marks = scan.getRawQuestionMarks();
		for (VariableReferenceScanner.Occurrence occurrence : scan.getOccurrences()) {
			while (escapeQuestionMarks && q < marks.size() && marks.get(q) < occurrence.start()) {
				jdbc.append(sql, copied, marks.get(q)).append("??");
				copied = marks.get(q) + 1;
				q++;
			}
			jdbc.append(sql, copied, occurrence.start()).append('?');
			copied = occurrence.end();
		}
		while (escapeQuestionMarks && q < marks.size()) {
			jdbc.append(sql, copied, marks.get(q)).append("??");
			copied = marks.get(q) + 1;
			q++;
		}
		jdbc.append(sql, copied, sql.length());
		return new PreparedSql(sql, jdbc.toString(), binds, referenced);
	}

	/** As {@link #prepare}, or a {@link PreparedSql} of the text as written when there is no reference. */
	public static PreparedSql prepareAlways(String sql, ScriptVariables variables, BooleanSupplier pgjdbc) throws BroadSQLException {
		PreparedSql prepared = prepare(sql, variables, pgjdbc);
		if (prepared != null) {
			return prepared;
		}
		if (pgjdbc != null && !VariableReferenceScanner.scan(sql).getRawQuestionMarks().isEmpty() && pgjdbc.getAsBoolean()) {
			// BroadSQL prepares this statement although it has no reference (the LET query): pgjdbc would read a raw
			// ? as a parameter, so it is escaped exactly as when references are present.
			return escapedForPgjdbc(sql);
		}
		return PreparedSql.unbound(sql);
	}

	private static PreparedSql escapedForPgjdbc(String sql) {
		StringBuilder jdbc = new StringBuilder(sql.length() + 4);
		int copied = 0;
		for (int mark : VariableReferenceScanner.scan(sql).getRawQuestionMarks()) {
			jdbc.append(sql, copied, mark).append("??");
			copied = mark + 1;
		}
		jdbc.append(sql, copied, sql.length());
		return new PreparedSql(sql, jdbc.toString(), List.of(), new LinkedHashMap<>());
	}

	/** The undefined-variable error (spec 9.4), with the API hint when an API variable of that name exists. */
	public static BroadSQLException undefined(String name) {
		String message = "Variable " + name + " is not defined.";
		if (ApiSessionVariablesHolder.isSet(name)) {
			message += " An API variable " + name + " exists; API variables (VAR) are not visible in SQL. Use LET to define a SQL scripting variable.";
		}
		return new BroadSQLException(message);
	}

	/** The malformed-reference error (spec 9.4). */
	public static BroadSQLException malformed(String text) {
		String message = "Malformed variable reference '" + text + "': a reference is ${name}, where name starts with a letter or _, contains only "
				+ "letters, digits and _ (at most " + VariableNames.MAX_LENGTH + " characters), and is not ENV, NULL, TRUE or FALSE";
		if (text.toUpperCase(java.util.Locale.ROOT).startsWith("${ENV:")) {
			message += ". ${ENV:...} is not supported in SQL scripting";
		}
		return new BroadSQLException(message);
	}
}
